### ISSUE TITLE
Trouble Authenticating with WebHelpDesk

### ISSUE THREAD

**Issue by bradybutcher** [corrionc/PS-WHD#1]
Hey Collin, writing from Brighton Schools. We are trying to implement the script to manage chromebooks in GAdmin and Help Desk. The script is throwing an "Exception: API Key, SessionKey or Credential Required" in powershell. We have generated an API key and pasted it into the $APIKey variable in the script, and it is not empty in the module. Any ideas on the workaround this?
![IMG_6202](https://user-images.githubusercontent.com/87883036/225947502-15466b20-a427-4c4d-9c0e-688eceb8ba73.jpg)

**Comment by bradybutcher** [comment]
uncommented the "Set-Variable -Scope Script -Name "WHDPassword" -Value $Password" line and error went away, to now allow me to scan SN. after scanning SN, now another error pops up saying that the "serialNumber, location, and networkName cannot be found on the object"

**Comment by corrionc** [comment]
My ability to help is going to be limited, as I do not have access to a instance of WHD.  I'd look a couple of things:

1)  After you've authenticated to WHD, confirm that you have successfully authenticated by doing something like Get-WHDAsset <int> and inspecting the output.  It should return something with a bunch of attributes.
2) Run the WHD cmdlets with a -debug tagged on to see if it works as expected.
3) Finally, inspect the asset number and make sure it matches the model of Chromebook that you're importing.
